spring.application.name=spring-boot-caching

spring.datasource.url=jdbc:h2:mem:weather_service_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Password
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.cache-names=weather